rules:
  - id: hardcoded-secret-detection
    pattern: $SECRET = "$VALUE"
    message: "Potential hardcoded secret detected"
    languages: [php]
    severity: WARNING

  - id: raw-sql-detection
    pattern: DB::select("SELECT * FROM users WHERE name = '$USER'")
    message: "Raw SQL detected — use parameterized queries to prevent SQL injection"
    languages: [php]
    severity: ERROR
