<?php

/**
 * breadcrumbs.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'home'             => 'Pagina principale',
    'budgets'          => 'Budget',
    'subscriptions'    => 'Abbonamenti',
    'transactions'     => 'Transazioni',
    'title_expenses'   => 'Uscite',
    'title_withdrawal' => 'Prelievi',
    'title_revenue'    => 'Redditi / entrate',
    'title_deposit'    => 'Versamenti',
    'title_transfer'   => 'Trasferimenti',
    'title_transfers'  => 'Trasferimenti',
    'edit_currency'    => 'Modifica valuta ":name"',
    'delete_currency'  => 'Elimina valuta ":name"',
    'newPiggyBank'     => 'Crea un nuovo salvadanaio',
    'edit_piggyBank'   => 'Modifica salvadanaio ":name"',
    'preferences'      => 'Preferenze',
    'profile'          => 'Profilo',
    'accounts'         => 'Conti',
    'changePassword'   => 'Cambia la tua password',
    'change_email'     => 'Cambia il tuo indirizzo email',
    'bills'            => 'Bollette',
    'newBill'          => 'Nuova bolletta',
    'edit_bill'        => 'Modifica bolletta ":name"',
    'delete_bill'      => 'Elimina bolletta ":name"',
    'reports'          => 'Resoconti',
    'search_result'    => 'Risultati di ricerca per ":query"',
    'withdrawal_list'  => 'Spese, uscite e prelievi',
    'Withdrawal_list'  => 'Uscite',
    'deposit_list'     => 'Redditi, entrate e depositi',
    'transfer_list'    => 'Trasferimenti',
    'transfers_list'   => 'Trasferimenti',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'reconciliation_list'    => 'Riconciliazioni',
    'create_withdrawal'      => 'Crea nuova uscita',
    'create_deposit'         => 'Crea nuova entrata',
    'create_transfer'        => 'Crea nuovo trasferimento',
    'create_new_transaction' => 'Crea una nuova transazione',
    'edit_journal'           => 'Modifica transazione ":description"',
    'edit_reconciliation'    => 'Modifica ":description"',
    'delete_journal'         => 'Elimina transazione ":description"',
    'delete_group'           => 'Elimina transazione ":description"',
    'tags'                   => 'Etichette',
    'createTag'              => 'Crea nuova etichetta',
    'edit_tag'               => 'Modifica etichetta ":tag"',
    'delete_tag'             => 'Elimina etichetta ":tag"',
    'delete_journal_link'    => 'Elimina il collegamento tra le transazioni',
    'edit_object_group'      => 'Modifica gruppo ":title"',
    'delete_object_group'    => 'Elimina gruppo ":title"',
    'logout_others'          => 'Esci dalle altre sessioni',
    'asset_accounts'         => 'Conti attività',
    'expense_accounts'       => 'Conti uscite',
    'revenue_accounts'       => 'Conti entrate',
    'liabilities_accounts'   => 'Passività',
    'placeholder'            => '[Placeholder]',
];
