<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'buttons'               => 'Botones',
    'icon'                  => 'Icono',
    'id'                    => 'ID',
    'create_date'           => 'Fecha de creación',
    'update_date'           => 'Fecha de modificación',
    'updated_at'            => 'Actualizado el',
    'balance_before'        => 'Balance antes de ',
    'balance_after'         => 'Balance después de la',
    'name'                  => 'Nombre',
    'role'                  => 'Rol',
    'currentBalance'        => 'Balance actual',
    'linked_to_rules'       => 'Reglas asociadas',
    'active'                => '¿Está Activo?',
    'percentage'            => 'pct.',
    'recurring_transaction' => 'Transacción Recurrente',
    'next_due'              => 'Próxima vez',
    'transaction_type'      => 'Tipo',
    'lastActivity'          => 'Última actividad',
    'balanceDiff'           => 'Diferencia de saldo',
    'other_meta_data'       => 'Otros metadatos',
    'invited_at'            => 'Invitada el',
    'expires'               => 'La invitación caduca',
    'invited_by'            => 'Invitado por',
    'invite_link'           => 'Enlace de invitación',
    'account_type'          => 'Tipo de cuenta',
    'created_at'            => 'Fecha de creación',
    'account'               => 'Cuenta',
    'external_url'          => 'URL externa',
    'matchingAmount'        => 'Cantidad',
    'destination'           => 'Destino',
    'source'                => 'Origen',
    'next_expected_match'   => 'Próxima coincidencia esperada',
    'automatch'             => '¿Buscar coincidencia automáticamente?',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'repeat_freq'             => 'Repetición:',
    'description'             => 'Descripción',
    'amount'                  => 'Cantidad',
    'date'                    => 'Fecha',
    'interest_date'           => 'Tasa de interés',
    'book_date'               => 'Fecha del libro de registro',
    'process_date'            => 'Fecha de procesamiento',
    'due_date'                => 'Fecha de vencimiento',
    'payment_date'            => 'Fecha de pago',
    'invoice_date'            => 'Fecha de la factura',
    'internal_reference'      => 'Referencia interna',
    'notes'                   => 'Notas',
    'from'                    => 'Desde',
    'piggy_bank'              => 'Alcancilla',
    'to'                      => 'Hasta',
    'budget'                  => 'Presupuesto',
    'category'                => 'Categoría',
    'bill'                    => 'Factura',
    'withdrawal'              => 'Gasto',
    'deposit'                 => 'Ingreso',
    'transfer'                => 'Trasferencia',
    'type'                    => 'Tipo',
    'completed'               => 'Completado',
    'iban'                    => 'IBAN',
    'account_number'          => 'Número de cuenta',
    'paid_current_period'     => 'Pagado este período',
    'email'                   => 'Correo electrónico',
    'registered_at'           => 'Registrado',
    'is_blocked'              => 'Bloqueado',
    'is_admin'                => '¿Es administrador?',
    'has_two_factor'          => 'Tiene 2FA',
    'blocked_code'            => 'Código de bloqueo',
    'source_account'          => 'Cuenta origen',
    'destination_account'     => 'Cuenta destino',
    'accounts_count'          => 'Número de cuentas',
    'journals_count'          => 'Número de transacciones',
    'attachments_count'       => 'Núm. de datos adjuntos',
    'bills_count'             => 'Número de facturas',
    'categories_count'        => 'Número de categorías',
    'budget_count'            => 'Número de presupuestos',
    'rule_and_groups_count'   => 'Número de reglas y grupos de reglas',
    'tags_count'              => 'Número de etiquetas',
    'tags'                    => 'Etiquetas',
    'inward'                  => 'Descripción interna',
    'outward'                 => 'Descripción externa',
    'number_of_transactions'  => 'Número de transacciones',
    'total_amount'            => 'Total',
    'sum'                     => 'Suma',
    'sum_excluding_transfers' => 'Suma (excluyendo transferencias)',
    'sum_withdrawals'         => 'Suma de gastos',
    'sum_deposits'            => 'Suma de ingresos',
    'sum_transfers'           => 'Suma de transferencias',
    'sum_reconciliations'     => 'Suma de reconciliaciones',
    'reconcile'               => 'Reconciliar',
    'sepa_ct_id'              => 'Identificador de extremo a extremo SEPA',
    'sepa_ct_op'              => 'Identificador de cuenta opuesta SEPA',
    'sepa_db'                 => 'Identificador de mandato SEPA',
    'sepa_country'            => 'País SEPA',
    'sepa_cc'                 => 'Código de limpieza SEPA',
    'sepa_ep'                 => 'Propósito externo SEPA',
    'sepa_ci'                 => 'Identificador de acreedor SEPA',
    'sepa_batch_id'           => 'ID de lote SEPA',
    'external_id'             => 'ID Externo',
    'account_at_bunq'         => 'Cuenta con bunq',
    'file_name'               => 'Nombre de fichero',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'file_size'           => 'Tamaño de fichero',
    'file_type'           => 'Tipo de fichero',
    'attached_to'         => 'Adjunto a',
    'file_exists'         => 'El fichero existe',
    'spectre_bank'        => 'Banco',
    'spectre_last_use'    => 'Último acceso',
    'spectre_status'      => 'Estado',
    'bunq_payment_id'     => 'ID de pago bunq',
    'repetitions'         => 'Repeticiones',
    'title'               => 'Título',
    'transaction_s'       => 'Transacción(es)',
    'field'               => 'Campo',
    'value'               => 'Valor',
    'interest'            => 'Interés',
    'interest_period'     => 'Período de interés',
    'liability_type'      => 'Tipo de pasivo',
    'liability_direction' => 'Pasivo entrada/salida',
    'end_date'            => 'Fecha fin',
    'payment_info'        => 'Información del pago',
    'expected_info'       => 'Siguiente transacción esperada',
    'start_date'          => 'Fecha de inicio',
    'trigger'             => 'Disparador',
    'response'            => 'Respuesta',
    'delivery'            => 'Entrega',
    'url'                 => 'URL',
    'secret'              => 'Secreto',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
