<?php
namespace Report;

use TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-26 at 07:52:22.
 */
class AccountControllerTest extends TestCase
{


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
    }

    /**
     * @covers FireflyIII\Http\Controllers\Report\AccountController::accountReport
     * Implement testAccountReport().
     */
    public function testAccountReport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
