<?php
/**
 * ChartReportControllerTest.php
 * Copyright (C) 2016 Sander Dorigo
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-19 at 15:39:57.
 */
class ChartReportControllerTest extends TestCase
{
    /**
     * @covers FireflyIII\Http\Controllers\Chart\ReportController::yearInOut
     * @todo   Implement testYearInOut().
     */
    public function testYearInOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\Chart\ReportController::yearInOutSummarized
     * @todo   Implement testYearInOutSummarized().
     */
    public function testYearInOutSummarized()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
