<?php
/**
 * ChartPiggyBankControllerTest.php
 * Copyright (C) 2016 Sander Dorigo
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-19 at 15:39:57.
 */
class ChartPiggyBankControllerTest extends TestCase
{

    /**
     * @covers FireflyIII\Http\Controllers\Chart\PiggyBankController::history
     */
    public function testHistory()
    {
        $this->be($this->user());
        $response = $this->call('GET', '/chart/piggy-bank/1');
        $this->assertEquals(200, $response->status());
    }
}
