<?php


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-20 at 07:15:07.
 */
class AccountControllerTest extends TestCase
{

    

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::create
     */
    public function testCreate()
    {
        $this->be($this->user());
        $this->call('GET', route('accounts.create', ['asset']));
        $this->assertResponseStatus(200);
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::edit
     * @todo   Implement testEdit().
     */
    public function testEdit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::show
     * @todo   Implement testShow().
     */
    public function testShow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::showWithDate
     * @todo   Implement testShowWithDate().
     */
    public function testShowWithDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::store
     * @todo   Implement testStore().
     */
    public function testStore()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\AccountController::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
