<?php


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-19 at 19:28:42.
 */
class JsonControllerTest extends TestCase
{
    /**
     * @var JsonController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::action
     * @todo   Implement testAction().
     */
    public function testAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::boxBillsPaid
     * @todo   Implement testBoxBillsPaid().
     */
    public function testBoxBillsPaid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::boxBillsUnpaid
     * @todo   Implement testBoxBillsUnpaid().
     */
    public function testBoxBillsUnpaid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::boxIn
     * @todo   Implement testBoxIn().
     */
    public function testBoxIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::boxOut
     * @todo   Implement testBoxOut().
     */
    public function testBoxOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::categories
     * @todo   Implement testCategories().
     */
    public function testCategories()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::endTour
     * @todo   Implement testEndTour().
     */
    public function testEndTour()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::expenseAccounts
     * @todo   Implement testExpenseAccounts().
     */
    public function testExpenseAccounts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::revenueAccounts
     * @todo   Implement testRevenueAccounts().
     */
    public function testRevenueAccounts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::tags
     * @todo   Implement testTags().
     */
    public function testTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::tour
     * @todo   Implement testTour().
     */
    public function testTour()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::transactionJournals
     * @todo   Implement testTransactionJournals().
     */
    public function testTransactionJournals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\JsonController::trigger
     * @todo   Implement testTrigger().
     */
    public function testTrigger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
