<?php
/**
 * PreferencesControllerTest.php
 * Copyright (C) 2016 Sander Dorigo
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 */


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-19 at 15:39:28.
 */
class PreferencesControllerTest extends TestCase
{

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::postIndex
     * @todo   Implement testPostIndex().
     */
    public function testPostIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
