<?php


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-19 at 19:28:42.
 */
class PreferencesControllerTest extends TestCase
{
    /**
     * @var PreferencesController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::code
     * @todo   Implement testCode().
     */
    public function testCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::deleteCode
     * @todo   Implement testDeleteCode().
     */
    public function testDeleteCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::postCode
     * @todo   Implement testPostCode().
     */
    public function testPostCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\PreferencesController::postIndex
     * @todo   Implement testPostIndex().
     */
    public function testPostIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
