<?php


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-20 at 07:15:12.
 */
class ProfileControllerTest extends TestCase
{


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
    }

    /**
     * @covers FireflyIII\Http\Controllers\ProfileController::changePassword
     * @todo   Implement testChangePassword().
     */
    public function testChangePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\ProfileController::deleteAccount
     * @todo   Implement testDeleteAccount().
     */
    public function testDeleteAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\ProfileController::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\ProfileController::postChangePassword
     * @todo   Implement testPostChangePassword().
     */
    public function testPostChangePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FireflyIII\Http\Controllers\ProfileController::postDeleteAccount
     * @todo   Implement testPostDeleteAccount().
     */
    public function testPostDeleteAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
