<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'buttons'               => 'Tombol',
    'icon'                  => 'Ikon',
    'id'                    => 'ID',
    'create_date'           => 'Dibuat pada',
    'update_date'           => 'Diperbarui pada',
    'updated_at'            => 'Diperbarui pada',
    'balance_before'        => 'Saldo Sebelumnya',
    'balance_after'         => 'Saldo setelahnya',
    'name'                  => 'Nama',
    'role'                  => 'Peran',
    'currentBalance'        => 'Saldo saat ini',
    'linked_to_rules'       => 'Aturan yang relevan',
    'active'                => 'Aktif?',
    'percentage'            => 'pct.',
    'recurring_transaction' => 'Transaksi berulang',
    'next_due'              => 'Jatuh tempo selanjutnya',
    'transaction_type'      => 'Tipe',
    'lastActivity'          => 'Aktifitas terakhir',
    'balanceDiff'           => 'Perbedaan saldo',
    'other_meta_data'       => 'Meta data lain',
    'invited_at'            => 'Invited at',
    'expires'               => 'Invitation expires',
    'invited_by'            => 'Invited by',
    'invite_link'           => 'Invite link',
    'account_type'          => 'Jenis akun',
    'created_at'            => 'Dibuat di',
    'account'               => 'Akun',
    'external_url'          => 'External URL',
    'matchingAmount'        => 'Jumlah',
    'destination'           => 'Tujuan',
    'source'                => 'Sumber',
    'next_expected_match'   => 'Transaksi yang diharapkan berikutnya',
    'automatch'             => 'Pencocokan otomatis?',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'repeat_freq'             => 'Berulang',
    'description'             => 'Deskripsi',
    'amount'                  => 'Jumlah',
    'date'                    => 'Tanggal',
    'interest_date'           => 'Tanggal Bunga',
    'book_date'               => 'Tanggal Buku',
    'process_date'            => 'Tanggal pemrosesan',
    'due_date'                => 'Tenggat waktu',
    'payment_date'            => 'Tanggal pembayaran',
    'invoice_date'            => 'Tanggal Faktur',
    'internal_reference'      => 'Referensi internal',
    'notes'                   => 'Catatan',
    'from'                    => 'Dari',
    'piggy_bank'              => 'Celengan',
    'to'                      => 'Untuk',
    'budget'                  => 'Anggaran',
    'category'                => 'Kategori',
    'bill'                    => 'Tagihan',
    'withdrawal'              => 'Penarikan',
    'deposit'                 => 'Simpanan',
    'transfer'                => 'Transfer',
    'type'                    => 'Jenis',
    'completed'               => 'Lengkap',
    'iban'                    => 'IBAN',
    'account_number'          => 'Account number',
    'paid_current_period'     => 'Membayar periode ini',
    'email'                   => 'Email',
    'registered_at'           => 'Terdaftar di',
    'is_blocked'              => 'Diblokir',
    'is_admin'                => 'Apakah admin',
    'has_two_factor'          => 'Memiliki 2FA',
    'blocked_code'            => 'Kode blok',
    'source_account'          => 'Akun sumber',
    'destination_account'     => 'Akun tujuan',
    'accounts_count'          => 'Jumlah rekening',
    'journals_count'          => 'Jumlah transaksi',
    'attachments_count'       => 'Jumlah lampiran',
    'bills_count'             => 'Jumlah tagihan',
    'categories_count'        => 'Jumlah kategori',
    'budget_count'            => 'Jumlah anggaran',
    'rule_and_groups_count'   => 'Jumlah aturan dan kelompok aturan',
    'tags_count'              => 'Jumlah label',
    'tags'                    => 'Label',
    'inward'                  => 'Deskripsi dalam',
    'outward'                 => 'Deskripsi luar',
    'number_of_transactions'  => 'Jumlah transaksi',
    'total_amount'            => 'Jumlah total',
    'sum'                     => 'Jumlah',
    'sum_excluding_transfers' => 'Jumlah (tidak termasuk transfer)',
    'sum_withdrawals'         => 'Jumlah penarikan',
    'sum_deposits'            => 'Jumlah simpanan',
    'sum_transfers'           => 'Jumlah transfer',
    'sum_reconciliations'     => 'Rekonsiliasi total',
    'reconcile'               => 'Menyesuaikan',
    'sepa_ct_id'              => 'Pengidentifikasi Ujung ke Ujung SEPA',
    'sepa_ct_op'              => 'Pengidentifikasi akun SEPA yang dapat diterapkan',
    'sepa_db'                 => 'Pengidentifikasi Mandat SEPA',
    'sepa_country'            => 'Negara SEPA',
    'sepa_cc'                 => 'Kode rekonsiliasi SEPA',
    'sepa_ep'                 => 'Tujuan Eksternal SEPA',
    'sepa_ci'                 => 'Pengenal Kreditur SEPA',
    'sepa_batch_id'           => 'ID Batch SEPA',
    'external_id'             => 'ID Eksternal',
    'account_at_bunq'         => 'Rekening dengan bunq',
    'file_name'               => 'Nama file',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'file_size'           => 'Ukuran file',
    'file_type'           => 'Jenis file',
    'attached_to'         => 'Melekat pada',
    'file_exists'         => 'File ada',
    'spectre_bank'        => 'Bank',
    'spectre_last_use'    => 'Login terakhir',
    'spectre_status'      => 'Status',
    'bunq_payment_id'     => 'bunq payment ID',
    'repetitions'         => 'Pengulangan',
    'title'               => 'Judul',
    'transaction_s'       => 'Transaksi',
    'field'               => 'Bidang',
    'value'               => 'Nilai',
    'interest'            => 'Bunga',
    'interest_period'     => 'Periode bunga',
    'liability_type'      => 'Jenis kewajiban',
    'liability_direction' => 'Kewajiban masuk/keluar',
    'end_date'            => 'Tanggal Selesai',
    'payment_info'        => 'Informasi Pembayaran',
    'expected_info'       => 'Perkiraan transaksi berikutnya',
    'start_date'          => 'Tanggal mulai',
    'trigger'             => 'Trigger',
    'response'            => 'Response',
    'delivery'            => 'Delivery',
    'url'                 => 'URL',
    'secret'              => 'Secret',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
