<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'no_demo_text'           => 'Lamento, não existe nenhuma explicação-demonstração extra para <abbr title=":route">esta página</abbr>.',
    'see_help_icon'          => 'No entanto, o ícone <i class="fa fa-question-circle"></i> no canto superior direito poderá dar mais informação.',
    'index'                  => 'Bem-vindo ao <strong>Firefly III</strong>! Nesta página poderá ver um resumo rápido das suas finanças. Para mais informações, verifique as contas &rarr; <a href=":asset">Contas de Ativos</a>, os <a href=":budgets">Orçamentos</a> e claro a página dos <a href=":reports">Relatórios</a>. Em alternativa dê uma volta pela plataforma e observe onde acaba por parar.',
    'accounts-index'         => 'Contas de ativos são as contas bancárias pessoais. Contas de despesas são contas onde se gasta dinheiro, como lojas e amigos. Contas de receitas são contas de onde se recebe dinheiro, como o salário, governo e outras fontes de rendimentos. Contas de passivos são onde as dividas e empréstimos tais como cartões de crédito ou créditos à habitação. Nesta página podes editá-los ou removê-los.',
    'budgets-index'          => 'Esta pagina dá-lhe uma visão geral sobre os seus orçamentos. A barra de topo mostra o montante disponível para ser orçamentado. Isto pode ser personalizado para qualquer período ao clicar no montante do lado direito. O montante que atualmente já gastou encontra-se exibido na barra abaixo. Mais abaixo, encontra as despesas por orçamento e o que orçamentou para cada uma delas.',
    'reports-index-start'    => 'O Firefly III suporta vários tipos de relatórios. Leia sobre eles ao clicar no ícone <i class="fa fa-question-circle"></i>, no canto superior direito.',
    'reports-index-examples' => 'Certifique-se de que vê estes exemplos: <a href=":one">uma visão geral mensal das finanças</a>, <a href=":two">visão geral anual das finanças</a> e <a href=":three">uma visão geral do orçamento</a>.',
    'currencies-index'       => 'O Firefly III suporta múltiplas moedas. Embora seja definido o Euro como moeda padrão, pode ser definido para o Dólar Americano ou outra. Como pode ver, foi incluída uma pequena seleção de moedas, mas, se assim o desejar, pode adicionar outras. No entanto, alterar a moeda padrão não vai alterar a moeda das transações já existentes. O Firefly III suporta o uso de múltiplas moedas em simultâneo.',
    'transactions-index'     => 'Estas despesas, depósitos e transferências não são particularmente imaginativas. Foram geradas automaticamente.',
    'piggy-banks-index'      => 'Como pode ver, existem três mealheiros. Use os botões mais e menos para atualizar o montante de dinheiro em cada mealheiro. Clica no nome do mealheiro para ver a administração de cada mealheiro.',
    'profile-index'          => 'Lembre-se que a plataforma demo reinicia a cada 4 horas. O seu acesso pode ser revogado a qualquer altura. Acontece automaticamente e não é um erro na plataforma.',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
