<?php

/**
 * demo.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */


declare(strict_types=1);

return [
    'no_demo_text'           => 'Lamentamos, nao existe uma explicacao-demonstracao extra para <abbr title=":route">esta pagina</abbr>.',
    'see_help_icon'          => 'No entanto, o icone <i class="fa fa-question-circle"></i> no canto superior direito pode te informar de mais.',
    'index'                  => 'Bem vindo ao <strong>Firefly III</strong>! Nesta pagina poderá ver um resumo rápido das suas finanças. Para mais informações, verifique as contas &rarr; <a href=":asset">Contas de Ativos</a>, os <a href=":budgets">Orçamentos</a> e claro a página dos <a href=":reports">Relatórios</a>. Em alternativa dê uma volta pela plataforma e observe onde acaba por parar.',
    'accounts-index'         => 'Contas de ativos são as contas bancárias pessoais. Contas de despesas são contas onde se gasta dinheiro, como lojas e amigos. Contas de receitas são contas que se recebe dinheiro, como o salário, governo e outras fontes de rendimentos. Contas de passivos são onde as dividas e empréstimos tais como um crédito bancários, hipotecas, crédito habitação. Nesta página podes editá-los ou removê-los.',
    'budgets-index'          => 'Esta pagina dá-lhe uma visão geral sobre os seus orçamentos. A barra de topo mostra o montante disponível para ser orçamentado. Isto pode ser personalizado para qualquer período ao clicar no montante do lado direito. O montante que atualmente já gastou encontra-se exibido na barra abaixo. Por baixo dela, encontra as despesas por orçamento e o que orçamentou de cada um deles.',
    'reports-index-start'    => 'O Firefly III suporta inúmeros tipos de relatórios. Leia melhor sobre eles ao clicar no ícone <i class="fa fa-question-circle"></i>, no canto superior direito.',
    'reports-index-examples' => 'Certifica-te que olhas estes exemplos: <a href=":one">visao geral das financas mensal</a>, <a href=":two">visao geral das financas anual</a> e <a href=":three">visao geral do orcamento</a>.',
    'currencies-index'       => 'O Firefly III suporta múltiplas moedas. No entanto é colocado o Euro como moeda padrão. Pode ser definido para Dólares Americanos entre outras. Como pode verificar, uma pequena seleção de moedas foram incluidas, no entanto, se desejar, pode adicionar outras. Alterar a moeda padrão não vai alterar a moeda padrão das transações já existentes. Contudo, o Firefly III suporta o uso de múltiplas moedas em simultâneo.',
    'transactions-index'     => 'Estas despesas, depósitos e transferências não são particularmente imaginativas. Foram geradas automaticamente.',
    'piggy-banks-index'      => 'Existem 3 mealheiros. Usa o botão mais e menos para atualizar o montante de dinheiro em cada mealheiro. Clica no nome do mealheiro para ver a administração de cada mealheiro.',
    'profile-index'          => 'Nao te esquecas que a plataforma demo reinicia a cada 4 horas. O teu acesso pode ser revogado a qualquer altura. Isto acontece automaticamente e nao e um problema na plataforma.',
];

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
