<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'buttons'               => 'Botões',
    'icon'                  => 'Ícone',
    'id'                    => 'ID',
    'create_date'           => 'Criado em',
    'update_date'           => 'Alterado em',
    'updated_at'            => 'Alterado em',
    'balance_before'        => 'Saldo antes',
    'balance_after'         => 'Saldo depois',
    'name'                  => 'Nome',
    'role'                  => 'Perfil',
    'currentBalance'        => 'Saldo atual',
    'linked_to_rules'       => 'Regras relevantes',
    'active'                => 'Esta ativo?',
    'percentage'            => '%.',
    'recurring_transaction' => 'Transação recorrente',
    'next_due'              => 'Próximo vencimento',
    'transaction_type'      => 'Tipo',
    'lastActivity'          => 'Última atividade',
    'balanceDiff'           => 'Diferença de saldo',
    'other_meta_data'       => 'Outros meta dados',
    'invited_at'            => 'Convidado em',
    'expires'               => 'O convite expira',
    'invited_by'            => 'Convidado por',
    'invite_link'           => 'Link do convite',
    'account_type'          => 'Tipo de conta',
    'created_at'            => 'Criado em',
    'account'               => 'Conta',
    'external_url'          => 'URL Externo',
    'matchingAmount'        => 'Montante',
    'destination'           => 'Destino',
    'source'                => 'Origem',
    'next_expected_match'   => 'Próxima correspondência esperada',
    'automatch'             => 'Auto correspondência?',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'repeat_freq'             => 'Repete',
    'description'             => 'Descrição',
    'amount'                  => 'Montante',
    'date'                    => 'Data',
    'interest_date'           => 'Data de juros',
    'book_date'               => 'Data de registo',
    'process_date'            => 'Data de processamento',
    'due_date'                => 'Data de vencimento',
    'payment_date'            => 'Data de pagamento',
    'invoice_date'            => 'Data da fatura',
    'internal_reference'      => 'Referência interna',
    'notes'                   => 'Notas',
    'from'                    => 'De',
    'piggy_bank'              => 'Mealheiro',
    'to'                      => 'Para',
    'budget'                  => 'Orcamento',
    'category'                => 'Categoria',
    'bill'                    => 'Encargo',
    'withdrawal'              => 'Levantamento',
    'deposit'                 => 'Depósito',
    'transfer'                => 'Transferência',
    'type'                    => 'Tipo',
    'completed'               => 'Concluído',
    'iban'                    => 'IBAN',
    'account_number'          => 'Número de conta',
    'paid_current_period'     => 'Pago este período',
    'email'                   => 'Email',
    'registered_at'           => 'Registado em',
    'is_blocked'              => 'Está bloqueado',
    'is_admin'                => 'Administrador',
    'has_two_factor'          => 'Tem 2FA',
    'blocked_code'            => 'Código de bloqueio',
    'source_account'          => 'Conta de origem',
    'destination_account'     => 'Conta de destino',
    'accounts_count'          => 'Número de contas',
    'journals_count'          => 'Número de transações',
    'attachments_count'       => 'Número de anexos',
    'bills_count'             => 'Número de encargos',
    'categories_count'        => 'Número de categorias',
    'budget_count'            => 'Número de orçamentos',
    'rule_and_groups_count'   => 'Número de regras e grupos de regras',
    'tags_count'              => 'Número de etiquetas',
    'tags'                    => 'Etiquetas',
    'inward'                  => 'Descrição interna',
    'outward'                 => 'Descrição externa',
    'number_of_transactions'  => 'Número de transações',
    'total_amount'            => 'Montante total',
    'sum'                     => 'Soma',
    'sum_excluding_transfers' => 'Soma (excluindo transferências)',
    'sum_withdrawals'         => 'Soma dos levantamentos',
    'sum_deposits'            => 'Soma dos depósitos',
    'sum_transfers'           => 'Soma das transferências',
    'sum_reconciliations'     => 'Soma das reconciliações',
    'reconcile'               => 'Reconciliação',
    'sepa_ct_id'              => 'SEPA Identificador ponta-a-ponta',
    'sepa_ct_op'              => 'Identificador SEPA da conta oposta',
    'sepa_db'                 => 'Mandato Identificador SEPA',
    'sepa_country'            => 'País SEPA',
    'sepa_cc'                 => 'SEPA Clearing Code',
    'sepa_ep'                 => 'Finalidade Externa SEPA',
    'sepa_ci'                 => 'Identificador do credor SEPA',
    'sepa_batch_id'           => 'ID do Lote SEPA',
    'external_id'             => 'ID Externo',
    'account_at_bunq'         => 'Conta no bunq',
    'file_name'               => 'Nome do ficheiro',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'file_size'           => 'Tamanho do ficheiro',
    'file_type'           => 'Tipo do ficheiro',
    'attached_to'         => 'Anexado a',
    'file_exists'         => 'O ficheiro existe',
    'spectre_bank'        => 'Banco',
    'spectre_last_use'    => 'Último início de sessão',
    'spectre_status'      => 'Estado',
    'bunq_payment_id'     => 'ID de pagamento bunq',
    'repetitions'         => 'Repetições',
    'title'               => 'Título',
    'transaction_s'       => 'Transação(ões)',
    'field'               => 'Campo',
    'value'               => 'Valor',
    'interest'            => 'Juro',
    'interest_period'     => 'Período de juros',
    'liability_type'      => 'Tipo de responsabilidade',
    'liability_direction' => 'Passivo entrada/fora',
    'end_date'            => 'Data do término',
    'payment_info'        => 'Informações de pagamento',
    'expected_info'       => 'Próxima transação esperada',
    'start_date'          => 'Data de inicio',
    'trigger'             => 'Gatilho',
    'response'            => 'Resposta',
    'delivery'            => 'Entrega',
    'url'                 => 'URL',
    'secret'              => 'Segredo',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
