<?php

/**
 * list.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'buttons'               => 'Knapper',
    'icon'                  => 'Ikon',
    'id'                    => 'ID',
    'create_date'           => 'Oprettet den',
    'update_date'           => 'Opdateret den',
    'updated_at'            => 'Opdateret den',
    'balance_before'        => 'Saldo før',
    'balance_after'         => 'Saldo efter',
    'name'                  => 'Navn',
    'role'                  => 'Rolle',
    'currentBalance'        => 'Nuværende saldo',
    'linked_to_rules'       => 'Relevante regler',
    'active'                => 'Aktiv?',
    'percentage'            => 'pct.',
    'recurring_transaction' => 'Periodisk transaktion',
    'next_due'              => 'Næste forfaldsdato',
    'transaction_type'      => 'Type',
    'lastActivity'          => 'Seneste aktivitet',
    'balanceDiff'           => 'Saldo forskel',
    'other_meta_data'       => 'Andre metadata',
    'invited_at'            => 'Inviteret den',
    'expires'               => 'Invitationen udløber',
    'invited_by'            => 'Inviteret af',
    'invite_link'           => 'Invitationslink',
    'account_type'          => 'Kontotype',
    'created_at'            => 'Oprettet den',
    'account'               => 'Konto',
    'external_url'          => 'Ekstern URL',
    'matchingAmount'        => 'Beløb',
    'destination'           => 'Destination',
    'source'                => 'Kilde',
    'next_expected_match'   => 'Næste forventede afstemning',
    'automatch'             => 'Auto afstem?',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'repeat_freq'             => 'Gentagelser',
    'description'             => 'Beskrivelse',
    'amount'                  => 'Beløb',
    'date'                    => 'Dato',
    'interest_date'           => 'Rentedato',
    'book_date'               => 'Bogføringsdato',
    'process_date'            => 'Behandlingsdato',
    'due_date'                => 'Forfaldsdato',
    'payment_date'            => 'Betalingsdato',
    'invoice_date'            => 'Fakturadato',
    'internal_reference'      => 'Intern reference',
    'notes'                   => 'Bemærkninger',
    'from'                    => 'Fra',
    'piggy_bank'              => '"Sparebøsse"',
    'to'                      => 'Til',
    'budget'                  => 'Budget',
    'category'                => 'Kategori',
    'bill'                    => 'Regning',
    'withdrawal'              => 'Hævning',
    'deposit'                 => 'Indbetaling',
    'transfer'                => 'Overførsel',
    'type'                    => 'Type',
    'completed'               => 'Gennemført',
    'iban'                    => 'IBAN',
    'account_number'          => 'Konto nummer',
    'paid_current_period'     => 'Betalt i denne periode',
    'email'                   => 'E-mail',
    'registered_at'           => 'Registreret den',
    'is_blocked'              => 'Er blokeret',
    'is_admin'                => 'Er administrator',
    'has_two_factor'          => 'Har 2FA',
    'blocked_code'            => 'Blok kode',
    'source_account'          => 'Kildekonto',
    'destination_account'     => 'Destinationskonto',
    'accounts_count'          => 'Antal konti',
    'journals_count'          => 'Antal transaktioner',
    'attachments_count'       => 'Antal vedhæftede filer',
    'bills_count'             => 'Antal regninger',
    'categories_count'        => 'Antal kategorier',
    'budget_count'            => 'Antal budgetter',
    'rule_and_groups_count'   => 'Antal regler og regelsætsgrupper',
    'tags_count'              => 'Antal tags',
    'tags'                    => 'Tags',
    'inward'                  => 'Indadgående beskrivelse',
    'outward'                 => 'Udgående beskrivelse',
    'number_of_transactions'  => 'Antal transaktioner',
    'total_amount'            => 'Samlet beløb',
    'sum'                     => 'Sum',
    'sum_excluding_transfers' => 'Summen (eksklusive overførsler)',
    'sum_withdrawals'         => 'Summen af hævninger',
    'sum_deposits'            => 'Summen af indskud',
    'sum_transfers'           => 'Summen af overførsler',
    'sum_reconciliations'     => 'Summen af afstemninger',
    'reconcile'               => 'Afstem',
    'sepa_ct_id'              => 'SEPA Slut til Slut Identifikator',
    'sepa_ct_op'              => 'SEPA Modsvarende Konto Identifikator',
    'sepa_db'                 => 'SEPA Mandat Identifikator',
    'sepa_country'            => 'SEPA Land',
    'sepa_cc'                 => 'SEPA Clearingskode',
    'sepa_ep'                 => 'SEPA Eksternt Formål',
    'sepa_ci'                 => 'SEPA Kreditor Identifikator',
    'sepa_batch_id'           => 'SEPA Batch ID',
    'external_id'             => 'Eksternt ID',
    'account_at_bunq'         => 'Konto hos bunq',
    'file_name'               => 'Filnavn',

    /*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

    'file_size'           => 'Filstørrelse',
    'file_type'           => 'Filtype',
    'attached_to'         => 'Vedhæftet til',
    'file_exists'         => 'Filen findes',
    'spectre_bank'        => 'Bank',
    'spectre_last_use'    => 'Seneste login',
    'spectre_status'      => 'Status',
    'bunq_payment_id'     => 'bunq betalings ID',
    'repetitions'         => 'Gentagelser',
    'title'               => 'Titel',
    'transaction_s'       => 'Transaktion(er)',
    'field'               => 'Felt',
    'value'               => 'Værdi',
    'interest'            => 'Renter',
    'interest_period'     => 'Renteperiode',
    'liability_type'      => 'Gældstype',
    'liability_direction' => 'Passiver ind/ud',
    'end_date'            => 'Slut dato',
    'payment_info'        => 'Betalings information',
    'expected_info'       => 'Næste forventede transaktion',
    'start_date'          => 'Start dato',
    'trigger'             => 'Udløser',
    'response'            => 'Svar',
    'delivery'            => 'Delivery',
    'url'                 => 'URL',
    'secret'              => 'Hemmelighed',
];
/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */
