<?php

/**
 * passwords.php
 * Copyright (c) 2019 james@firefly-iii.org
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY.
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * YOUR PR WITH CHANGES TO THIS FILE WILL BE REJECTED!
 *
 * GO TO CROWDIN TO FIX OR CHANGE TRANSLATIONS!
 *
 * https://crowdin.com/project/firefly-iii
 *
 */

declare(strict_types=1);

return [
    'password' => 'Şifreniz en az altı karakter olmalıdır ve onayla eşleşmelidir.',
    'user'     => 'Bu e-posta adresine sahip bir kullanıcı bulunamadı.',
    'token'    => 'Bu şifre sıfırlama güvenlik anahtarı geçersiz.',
    'sent'     => 'Şifre sıfırlama linkini e-posta adresinize gönderdik!',
    'reset'    => 'Şifreniz sıfırlandı!',
    'blocked'  => 'Yine de iyi denemeydi.',
];
