name: DAST Scanning for Firefly App

# This workflow will run on every push to main, develop, and feature branches
on:
  push:
    branches:
      - main
      - develop
      - "feature/*" # Run this on all feature branches

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Java runtime (required by ZAP)
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

      # Install Docker if not installed (it may be installed already in Ubuntu GitHub runner)
      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io

      # Run ZAP with Docker
      - name: Run OWASP ZAP with Docker
        run: |
          docker pull owasp/zap2docker-stable
          docker run -d -p 8080:8080 owasp/zap2docker-stable zap.sh -daemon -port 8080
          sleep 30  # Allow time for ZAP to start

      # Run OWASP ZAP quick scan
      - name: Run OWASP ZAP scan
        run: |
          zap-cli quick-scan --url http://localhost:8080 # Ensure your app is running on localhost:8080 for ZAP to scan

      # Set up Burp Suite (optional step for additional scanning)
      - name: Set up Burp Suite
        run: |
          docker pull ports/swigger/burp-suite
          docker run -d -p 8080:8080 ports/swigger/burp-suite

      # Run Burp Suite scan (optional)
      - name: Run Burp Suite scan
        run: |
          docker exec -i burp /bin/bash -c "scan --target http://localhost:8080"
