name: DAST Scanning for Firefly App

# This workflow will run on every push
on:
  push:
    branches:
      - "*" # Run this on all branches. You can replace '*' with specific branches if required.

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run OWASP ZAP scan
      - name: Set up OWASP ZAP
        run: |
          sudo apt-get install zaproxy
          zap-cli start

      - name: Run OWASP ZAP scan
        run: |
          zap-cli quick-scan --url http://localhost:8080

      # Run Burp Suite Scan
      - name: Set up Burp Suite
        run: |
          docker pull ports/swigger/burp-suite
          docker run -d -p 8080:8080 ports/swigger/burp-suite

      - name: Run Burp Suite scan
        run: |
          # Example, can be customized with Burp Suite API commands
          docker exec -i burp /bin/bash -c "scan --target http://localhost:8080"
