name: DAST Scanning for Firefly App

# This workflow will run on every push
on:
  push:
    branches:
      - main
      - develop
      - "feature/*" # Run this on all branches. You can replace '*' with specific branches if required.

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run OWASP ZAP scan
      - name: Set up OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy
          zaproxy & # Start ZAP in the background
          sleep 30 # Give ZAP some time to initialize

      - name: Run OWASP ZAP scan
        run: |
          zap-cli quick-scan --url http://localhost:8080

      # Run Burp Suite Scan
      - name: Set up Burp Suite (Docker)
        run: |
          docker pull portswigger/burp-suite
          docker run -d --name burp -p 8080:8080 portswigger/burp-suite

      - name: Run Burp Suite scan
        run: |
          # Ensure the app is ready for Burp Suite to start scanning
          docker exec -i burp /bin/bash -c "scan --target http://localhost:8080"
