name: UI Tests on Pull Request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Firefly III repository (PR code)
        uses: actions/checkout@v4

      - name: Checkout Firefly-UI (tests repo)
        uses: actions/checkout@v4
        with:
          repository: tmeraslan/firefly-UI
          path: firefly-UI

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # מתקינים Chrome בצורה נקייה (ללא apt-key / ללא chromedriver ידני)
      - name: Setup Chrome (stable)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd firefly-UI
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Selenium Manager זמין מ-4.13+
          pip install "selenium>=4.13" pillow pytest pytest-timeout

      - name: Show versions (debug)
        run: |
          google-chrome --version || true
          python -c "import selenium,sys; print('selenium', selenium.__version__); print(sys.version)"

      # מחכים שהשרת יהיה זמין כדי שהטסטים לא "ייתקעו" בניווט הראשון
      - name: Wait for Firefly to be ready
        env:
          # עדיף לשים את ה-URL כ-Repository Variable בשם FIREFLY_URL
          FIREFLY_URL: ${{ vars.FIREFLY_URL }}
        run: |
          if [ -z "${FIREFLY_URL}" ]; then
            echo "❌ FIREFLY_URL is not set. Set it under Settings → Variables (e.g. http://34.244.228.75:8082)"
            exit 1
          fi
          echo "Waiting for ${FIREFLY_URL}..."
          for i in $(seq 1 40); do
            if curl -fsSL -o /dev/null "${FIREFLY_URL}/login" || curl -fsSL -o /dev/null "${FIREFLY_URL}/api/v1/ping"; then
              echo "✅ Firefly is reachable"
              exit 0
            fi
            echo "Attempt $i/40: not ready, sleeping 3s..."
            sleep 3
          done
          echo "❌ Firefly did not become ready."
          curl -I "${FIREFLY_URL}/login" || true
          exit 1

      - name: Run Selenium UI tests (headless)
        env:
          CI: "true"
          HEADLESS: "true"
          FIREFLY_URL: ${{ vars.FIREFLY_URL }}   # למשל: http://34.244.228.75:8082
          EMAIL: ${{ secrets.FIREFLY_EMAIL }}
          PASSWORD: ${{ secrets.FIREFLY_PASSWORD }}
          PYTHONUNBUFFERED: "1"
        run: |
          cd firefly-UI
          # timeout לכל טסט כדי שלא ייתקעו לנצח
          pytest tests/ -v --disable-warnings --timeout=120

      - name: Upload test artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-artifacts
          path: |
            firefly-UI/reports/**
            firefly-UI/screenshots/**
          if-no-files-found: ignore

